version: '3.1'

services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: user_password
      POSTGRES_USER: db_user
      POSTGRES_DB: db_name
    ports:
      - "5432:5432"


